//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspTeleBotSharp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int Id { get; set; }
        public string replyMarkupBox { get; set; }
        public string Text { get; set; }
        public Nullable<int> replyToMessageId { get; set; }
        public string box { get; set; }
        public string Image { get; set; }
        public string Type { get; set; }
        public string file { get; set; }
    }
}
