// <auto-generated />
namespace AspTeleBotSharp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewQues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewQues));
        
        string IMigrationMetadata.Id
        {
            get { return "202108220107460_NewQues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
